# Generated by Django 2.1.5 on 2019-01-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtilceUpDown',
            new_name='ArticleUpDown',
        ),
    ]
