# Generated by Django 2.0.10 on 2019-03-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190301_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'blog')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('title', 'blog')},
        ),
    ]
